### ISSUE TITLE
Avatar is Not URL

### ISSUE THREAD

**Issue by bayuirfan52** [nurchulis/learning-API#1]
Seharusnya data dari "avatar" adalah url dari file gambar tersebut. Bukan langsung pada filenya

![screenshot_20190305_142354](https://user-images.githubusercontent.com/27877049/53790580-d6ce6300-3f59-11e9-9721-fec29d2d8e2e.png)

**Comment by nurchulis** [comment]
![DeepinScreenshot_select-area_20190310231259](https://user-images.githubusercontent.com/32959136/54087860-1649e480-438a-11e9-9b48-706e33ef9fcd.png)

Syudah ...harus Di upload dlu gambar nya kalo user baru default ... u must update photo profile first if want to change
